# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lavalog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lavalog

    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'Charts'
    pod 'AlamofireImage'
    pod 'DeviceKit', '~> 1.3'
    pod 'AwesomeCache'
    pod 'Spring', '~> 1.0.3'
   #  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
    pod 'ReachabilitySwift', '~> 3'

end
